version: '3.8'

services:
  user-db:
    image: postgres:13-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: users_db
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "29092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
    healthcheck:
       test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
       interval: 5s
       timeout: 10s
       retries: 10
       start_period: 15s
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  post-db:
    image: postgres:13-alpine
    container_name: post-db
    environment:
      POSTGRES_USER: post_service
      POSTGRES_PASSWORD: post_password
      POSTGRES_DB: posts_db
    volumes:
      - post-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U post_service -d posts_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user_service
    container_name: user-service
    environment:
      DATABASE_URL: postgresql://user_service:user_password@user-db:5432/users_db
      PRIVATE_KEY_PATH: /app/private_key.pem
      PUBLIC_KEY_PATH: /app/public_key.pem
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "5001:5001"
    volumes:
      - ./user_service/private_key.pem:/app/private_key.pem
      - ./user_service/public_key.pem:/app/public_key.pem

  post-service:
    build: ./post_service
    container_name: post-service
    environment:
      DATABASE_URL: postgresql://post_service:post_password@post-db:5432/posts_db
      GRPC_PORT: 50051
    depends_on:
      post-db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "50051:50051"
    volumes:
      - ./proto:/app/proto
    command: ["python", "post_service.py"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    networks:
      - app-network
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
       CLICKHOUSE_DB: stats_db
       CLICKHOUSE_USER: default
       CLICKHOUSE_PASSWORD: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  statistics-service:
    build: ./statistics_service
    container_name: statistics-service
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: stats_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GRPC_PORT: 50052
    depends_on:
      - clickhouse
      - kafka
    networks:
      - app-network
    ports:
      - "50052:50052"
    volumes:
      - ./proto:/app/proto
    command: ["python", "statistics_service.py"]

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    environment:
      USER_SERVICE_URL: http://user-service:5001
      POST_SERVICE_HOST: post-service
      POST_SERVICE_PORT: 50051
      STATS_SERVICE_HOST: statistics-service
      STATS_SERVICE_PORT: 50052
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      user-service:
        condition: service_started
      post-service:
        condition: service_started
      statistics-service:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - ./user_service/public_key.pem:/app/public_key.pem
      - ./proto:/app/proto
    command: ["./wait-for-it.sh", "user-service:5001", "--", "python", "api_gateway.py"]

volumes:
  user-db-data:
  post-db-data:
  clickhouse-data:
networks:
  app-network:
    driver: bridge
